[tool.isort]
profile = "black"
[tool.pylint.MAIN]
load-plugins = [
    "pylint.extensions.docparams"
]
[tool.pylint.MESSAGES-CONTROL]
disable = [
    "invalid-name",
]
[tool.flake8]
max-line-length = 88
max-doc-length = 88
count = true
docstring-convention = "numpy"
require-plugins = [
    "flake8-pydocstyle",
    "flake8-pylint",
]
extend-select = [
    "D417",
]
