name: fortius-ant
summary: FortiusANT by WouterJD
description: FortiusANT BY WouterJD
grade: devel
confinement: devmode
base: core20
architectures:
  - build-on: [amd64]
adopt-info: fortius-ant
build-packages:
  - libffi-dev
  - libgstreamer-plugins-base1.0-0
  - libnotify4
  - libsdl2-2.0-0
  - libwebkit2gtk-4.0-dev
  - libjavascriptcoregtk-4.0-dev
  - libegl-dev
  - python3-setuptools
apps:
  fortius-ant:
    command: bin/fortius-ant
    plugs:
      - raw-usb

parts:
  fortius-ant:
    plugin: python
    requirements: [snap-requirements.txt]
    source: https://github.com/slaclau/FortiusANT.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags --always --long --match [[:digit:]]* --exclude *ubuntu*)"
      echo "__version__ = "$(git describe --tags --always --long --match [[:digit:]]* --exclude *ubuntu*)"" >> fortius_ant/_snapversion.py
      ls fortius_ant
      cat fortius_ant/_snapversion.py
    stage-packages:
      - libusb-1.0-0
      - libasound2
      - libasyncns0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatomic1
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libdrm2
      - libegl1
      - libenchant-2-2
      - libepoxy0
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgudev-1.0-0
      - libharfbuzz-icu0
      - libharfbuzz0b
      - libhyphen0
      - libice6
      - libicu66
      - libjavascriptcoregtk-4.0-18
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - libnotify4
      - libogg0
      - libopengl0
      - libopenjp2-7
      - liborc-0.4-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre2-32-0
      - libpixman-1-0
      - libpng16-16
      - libpsl5
      - libpulse0
      - libsdl2-2.0-0
      - libsecret-1-0
      - libsm6
      - libsndfile1
      - libsoup2.4-1
      - libthai0
      - libtiff5
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libwebkit2gtk-4.0-37
      - libwebp6
      - libwebpdemux2
      - libwoff1
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxss1
      - libxtst6
      - libxxf86vm1

