name: fortius-ant
summary: FortiusANT by WouterJD
description: FortiusANT BY WouterJD
version: git
grade: devel
confinement: devmode
base: core20
architectures:
  - build-on: [amd64]

build-packages:
  - libffi-dev
  - libgstreamer-plugins-base1.0-0
  - libnotify4
  - libsdl2-2.0-0
  - libwebkit2gtk-4.0-dev
  - libjavascriptcoregtk-4.0-dev
  - libegl-dev

apps:
  fortius-ant:
    command: bin/fortius-ant

parts:
  fortius-ant:
    plugin: python
    requirements: [snap-requirements.txt]
    source: https://github.com/slaclau/FortiusANT.git

