name: fortius-ant
summary: FortiusANT by WouterJD
description: FortiusANT BY WouterJD
version: git
grade: devel
confinement: devmode
base: core22
architectures:
  - build-on: [amd64]

apps:
  fortius-ant:
    command: bin/fortius-ant

parts:
  fortius-ant:
    plugin: python
    python-requirements: [snap-requirements.txt]
    source: https://github.com/slaclau/FortiusANT.git

