name: fortius-ant
summary: FortiusANT by WouterJD
descriptiom: FortiusANT BY WouterJD
version: git
grade: unstable
confinement: devmode
base: core22
architectures:
  - build-on: [amd64]

apps:
  fortius-ant:
    command: bin/fortius-ant

parts:
  fortius-ant:
    plugin: python
    source: https://github.com/slaclau/FortiusANT.git

