name: "Build debian packages"

on: 
  push:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add dh-virtualenv repository if needed
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
          sudo apt update
      - name: Install build dependencies
        run: |
          sudo mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
      - name: Check system python version
        run: |
          echo "useSystemPython=$(python3 useSystemPython.py)" >> $GITHUB_ENV
          echo "${{env.useSystemPython}}" 
      - name: Get python requirements
        run: |
          export useSystemPython=$(python3 useSystemPython.py)
          if [ "$useSystemPython" = "yes" ]
          then export ver=3
          else export ver=3.9
          fi
          sudo apt-get install -y python$ver
          python$ver updateChangelog.py
          python$ver wxPython-source.py
          mkdir pip_local
          python$ver -m pip install -U setuptools attrdict3
          python$ver setup.py bdist_wheel --dist-dir=pip_local
          python$ver -m pip download --no-binary=:all: --destination-directory pip_local -r requirements.txt
      - name: Build and sign source and binary
        run: |
          GPG_KEY_ID=$(echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --import-options show-only --import | sed -n '2s/^\s*//p')
          echo $GPG_KEY_ID
          echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --batch --import
          sed -i '1d' requirements.txt
          dpkg-buildpackage -S -sa --compression=xz --compression-level=1
          dpkg-buildpackage -b
          mv ../fortius-ant_*.* .
      - name: Install package
        run: |
          sudo apt install ./fortius-ant*.deb
      - name: Check installed versions
        run: |
          fortius-ant --version
          explorant --version
      - name: Upload debian package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            fortius-ant*.deb
            fortius-ant*.dsc
            fortius-ant*.tar.xz
            fortius-ant*.changes
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: fortius-ant*.deb
          prerelease: true
        if: contains(github.ref_name,'ubuntu') && github.ref_type == 'tag'
      - name: Get root release
        run: |
          echo "SHORT_TAG=$(echo ${{ github.ref_name }} | sed -re 's/-[0-9]+ubuntu[0-9]+//g')" >> $GITHUB_ENV
          echo ${{ env.SHORT_TAG }}
      - name: Update main release
        uses: softprops/action-gh-release@v1
        with:
          files: fortius-ant*.deb
          tag_name: ${{ env.SHORT_TAG }}
          body: "Updated to include ${{ github.ref_name }}"
          append_body: true
        if: contains(github.ref_name,'ubuntu') && github.ref_type == 'tag'
      - name: Publish package to prerelease PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-pre fortius-ant*source.changes
        if: github.ref == 'refs/heads/master'
      - name: Publish package to develop PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-develop fortius-ant*source.changes
        if: github.ref == 'refs/heads/develop'
      - name: Publish package to PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-pre fortius-ant*source.changes
        if: contains(github.ref_name,'ubuntu') && github.ref_type == 'tag'

permissions:
  contents: write
