name: "Build debian packages"

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Add dh-virtualenv repository if needed
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
          sudo apt update
      - name: Install build dependencies
        run: |
          sudo apt install debhelper dh-virtualenv
      - name: Check system python version
        run: echo "useSystemPython=$(python3 useSystemPython.py)" >> $GITHUB_ENV
      - name: Install system python packages
        if: ${{ env.useSystemPython == 'yes' }}
        run: |
          sudo apt install python3 python3-dev python3-distutils python3-venv
      - name: Install python3.9 packages
        if: ${{ env.useSystemPython != 'yes' }}
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.9 python3.9-dev python3.9-distutils python3.9-venv
      - name: Install needed libraries
        run: |
          sudo apt install libgstreamer-plugins-base1.0-0 libnotify4 libsdl2-2.0-0 libwebkit2gtk-4.0-dev libjavascriptcoregtk-4.0-dev libegl-dev
      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b
      - name: Install and test package
        run: |
          sudo dpkg -i ../fortius_ant*.deb
          timeout 10 fortius-ant >> log.txt
      - name: Upload debian package
        uses: actions/upload-artifact@v3
        with:
          name: matrix.os
          path: /home/runner/work/FortiusANT/fortius_ant*.deb
