name: "Build debian packages"

on: 
  push:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        codename: [focal, jammy, kinetic, lunar]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get build dependencies
        run: |
          sudo apt install pbuilder devscripts equivs
          sudo mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
      - name: Make source
        run: |
          python3 updateChangelog.py ${{ matrix.codename }}
          dpkg-buildpackage -S -sa
          mkdir source
          mv ../python*.* source/
      - name: Import key
        run: |
          GPG_KEY_ID=$(echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --import-options show-only --import | sed -n '2s/^\s*//p')
          echo $GPG_KEY_ID
          echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --batch --import
          debsign source/*.changes
      - name: Build
        run: |
          sudo pbuilder create \
            --distribution ${{ matrix.codename }}
          sudo pbuilder build \
            --distribution ${{ matrix.codename }} \
            --buildresult .. \
            source/*dsc
          mkdir binary
          mv ../python*.* binary/
      - name: Install
        run: |
          sudo add-apt-repository ppa:slaclau/ppa-pre
          sudo apt update
          sudo apt install ./binary/python3-fortius-ant*.deb
      - name: Check installed versions
        run: |
          fortius-ant --version
          explorant --version
      - name: Upload debian package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.codename }}
          path: |
            source
            binary
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: binary/*.deb
          prerelease: true
        if: contains(github.ref_name,'ubuntu') && github.ref_type == 'tag'
      - name: Get root release
        run: |
          echo "SHORT_TAG=$(echo ${{ github.ref_name }} | sed -re 's/-[0-9]+//g')" >> $GITHUB_ENV
          echo ${{ env.SHORT_TAG }}
      - name: Update main release
        uses: softprops/action-gh-release@v1
        with:
          files: binary/*.deb
          tag_name: ${{ env.SHORT_TAG }}
          body: "Updated to include ${{ github.ref_name }}"
          append_body: true
        if: contains(github.ref_name,'-') && github.ref_type == 'tag'
      - name: Publish package to prerelease PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-pre source/*source.changes
        if: github.ref == 'refs/heads/master'
      - name: Publish package to develop PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-develop source/*source.changes
        if: github.ref == 'refs/heads/develop'
      - name: Publish package to PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-pre source/*source.changes
        if: contains(github.ref_name,'-') && github.ref_type == 'tag'

permissions:
  contents: write
