name: Build snap

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build snap
        uses: snapcore/action-build@v1
        id: build
      - name: Install snap
        run: |
          sudo snap install --devmode ${{ steps.build.outputs.snap }}
      - name: Check installed versions
        run: |
          fortius-ant --version
          fortius-ant.explorant --version
      - name: Upload snap
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.build.outputs.snap }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.snap }}
        if: !${{ contains(github.ref_name,'ubuntu') }} && github.ref_type == 'tag'
      - name: Publish snap to edge
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
        if: github.ref == 'refs/heads/master'
      - name: Publish snap to beta
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
        if: !${{ contains(github.ref_name,'ubuntu') }} && github.ref_type == 'tag'
        
permissions:
  contents: write  
