name: "deptry"

on: 
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install python packages
        run: |
          python3 wxPython-source.py
          python3 -m pip install -r requirements.txt -r wxPython-source.txt
          python3 -m pip install .
      - name: Check dependencies
        continue-on-error: true
        run: |
          pip install deptry
          deptry src --json-output deptry.json
      - name: Convert report
        if: always()
        run: |
          python scripts/deptry2md.py deptry.json "deptry report" >> deptry.md
          cat deptry.md >> $GITHUB_STEP_SUMMARY
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: deptry
          path: |
            deptry.json
            deptry.md
