name: build in docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          cd docker
          docker build . --build-arg DISTRIBUTION=lunar