name: build in docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        codename: [kinetic, jammy, focal]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          mkdir output
          docker build . --build-arg DISTRIBUTION=${{ matrix.codename }} -t image 
          docker run image -v output:/output
          