name: build in docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        codename: [lunar, kinetic, jammy, focal]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build 
        run: |
          mkdir output
          docker build . --build-arg DISTRIBUTION=${{ matrix.codename }} -t image 
          docker run -v output:/output image
      - name: Install package
        run: |
          ls ./output
          sudo apt install ./output/fortius-ant*.deb
      - name: Check installed versions
        run: |
          fortius-ant --version
          explorant --version
      - name: Upload debian package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            output/fortius-ant*.deb
            output/fortius-ant*.dsc
            output/fortius-ant*.tar.xz
            output/fortius-ant*.changes