name: "lint"

on: 
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check system python version
        run: |
          echo "useSystemPython=$(python3 useSystemPython.py)" >> $GITHUB_ENV
          echo "${{env.useSystemPython}}"
      - name: Install system python packages
        if: ${{ env.useSystemPython == 'yes' }}
        run: |
          sudo apt install python3 python3-dev python3-distutils python3-venv
          python3 wxPython-source.py
          python3 -m pip install -r requirements.txt
          python3 -m pip install .
          python3 -m venv venv
      - name: Install python3.9 packages
        if: ${{ env.useSystemPython != 'yes' }}
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.9 python3.9-dev python3.9-distutils python3.9-venv
          python3.9 wxPython-source.py
          python3.9 -m venv venv
      - name: Install into venv
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install .
      - name: flake8
        if: always()
        run: |
          pip install flake8 flake8-json
          deptry fortius_ant --output=json --output-file=flake8.json
      - name: Convert report
        if: always()
        run: |
          python scripts/flake82md.py flake8.json "flake8 report" >> flake8.md
          cat flake8.md >> $GITHUB_STEP_SUMMARY
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flake8
          path: |
            flake8.json
            flake8.md
