name: "lint"

on: 
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: flake8
        if: always()
        run: |
          pip install flake8 flake8-json
          flake8 fortius_ant --format=json >> flake8.json
      - name: black
        if: always()
        run: |
          pip install black
          black --check fortius_ant
      - name: Convert report
        if: always()
        run: |
          python scripts/flake82md.py flake8.json "flake8 report" >> flake8.md
          cat flake8.md >> $GITHUB_STEP_SUMMARY
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flake8
          path: |
            flake8.json
            flake8.md
