name: "Test pip install"

on: 
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check system python version
        run: |
          echo "useSystemPython=$(python3 useSystemPython.py)" >> $GITHUB_ENV
          echo "${{env.useSystemPython}}"
      - name: Install system python packages
        if: ${{ env.useSystemPython == 'yes' }}
        run: |
          sudo apt install python3 python3-dev python3-distutils python3-venv
          python3 wxPython-source.py
          python3 -m pip install -r requirements.txt
          python3 -m pip install .
          python3 -m venv venv
      - name: Install python3.9 packages
        if: ${{ env.useSystemPython != 'yes' }}
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.9 python3.9-dev python3.9-distutils python3.9-venv
          python3.9 wxPython-source.py
          python3.9 -m pip install -r requirements.txt
          python3.9 -m pip install .
          python3.9 -m venv venv
      - name: Install needed libraries
        run: |
          sudo apt install libgstreamer-plugins-base1.0-0 libnotify4 libsdl2-2.0-0 libwebkit2gtk-4.0-dev libjavascriptcoregtk-4.0-dev libegl-dev
      - name: Get version
        run: |
          fortius-ant --version
          explorant --version
      - name: Check pip install
        if: always()
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install .
          fortius-ant --version
      - name: Check dependencies
        if: always()
        run: |
          pip install deptry
          deptry fortius_ant --json-output deptry.json
      - name: Convert report
        if: always()
        run: |
          python scripts/deptry2md.py deptry.json >> deptry.md
          cat deptry.md >> $GITHUB_STEP_SUMMARY
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: json
          path: |
            deptry.json
