name: "pytest"

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install python packages
        run: |
          python3 wxPython-source.py
          python3 -m pip install -r requirements.txt -r wxPython-source.txt
          python3 -m pip install -e .
      - name: Install pytest
        run: pip install -r pytest-requirements.txt
      - name: Test
        run: pytest --md-report --md-report-color never --verbose --md-report-output=pytest.md
      - name: Report
        if: always()
        run: cat pytest.md >> $GITHUB_STEP_SUMMARY
      - name: Test & publish code coverage
        if: always()
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE }}
        with:
          coverageCommand: pytest --cov=src tests --cov-report=xml
