name: "Release debian packages"

on:
  push:
#    tags:
#      - "*.*-*ubuntu*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add dh-virtualenv repository if needed
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
          sudo apt update
      - name: Install build dependencies
        run: |
          sudo apt install debhelper dh-virtualenv
      - name: Check system python version
        run: |
          echo "useSystemPython=$(python3 useSystemPython.py)" >> $GITHUB_ENV
          echo "${{env.useSystemPython}}"
      - name: Install system python packages
        if: ${{ env.useSystemPython == 'yes' }}
        run: |
          sudo apt install python3 python3-dev python3-distutils python3-venv
      - name: Install python3.9 packages
        if: ${{ env.useSystemPython != 'yes' }}
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.9 python3.9-dev python3.9-distutils python3.9-venv
      - name: Install needed libraries
        run: |
          sudo apt install libgstreamer-plugins-base1.0-0 libnotify4 libsdl2-2.0-0 libwebkit2gtk-4.0-dev libjavascriptcoregtk-4.0-dev libegl-dev
      - name: Build package
        run: |
          dpkg-buildpackage -us -uc
          mv ../fortius-ant*.deb .
          mv ../fortius-ant*.dsc .
          mv ../fortius-ant*.changes .
      - name: Install package
        run: |
          sudo apt install ./fortius-ant*.deb
      - name: Upload debian package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            fortius-ant*.deb
            fortius-ant*.dsc
            fortius-ant*.changes
      - name: Get package
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.os }}
      - name: tar package
        run: |
          tar cf ${{ matrix.os }}.tar ${{ matrix.os }}
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: ${{ matrix.os }}.tar
      - name: Build source package
        run: |
          ./buildSource.sh
          mkdir ../debuild
          mv ../*tar.gz ../debuild/
          tar xf ../debuild/*tar.gz
      - name: Publish focal package
        run: |
          dput ppa:slaclau/ppa fortius_ant*source.changes
        if: matrix.os == 'ubuntu-20.04'
      - name: Publish jammy package
        run: |
          dput ppa:slaclau/ppa fortius_ant*source.changes
        if: matrix.os == 'ubuntu-22.04'
permissions:
  contents: write
